admin_product_wg_image_upload:
    path: webstrumgallery/upload/{productId}
    methods: [POST]
    defaults:
      _controller: 'WebstrumGallery\Controller\ImageController::uploadAction'
admin_product_wg_image_delete:
    path: webstrumgallery/delete/{imageId}
    methods: [DELETE]
    defaults:
      _controller: 'WebstrumGallery\Controller\ImageController::deleteAction'

admin_product_wg_image_positions:
    path: webstrumgallery/positions/{productId}
    methods: [POST]
    defaults:
      _controller: 'WebstrumGallery\Controller\ImageController::updatePositionsAction'