services:
  webstrum_gallery.repository.image_repository:
    class: WebstrumGallery\Repository\ImageRepository
    public: true
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - WebstrumGallery\Entity\WebstrumGalleryImage

  webstrum_gallery.service.image_validator:
    class: WebstrumGallery\Service\ImageValidator

  webstrum_gallery.service.image_service:
    class: WebstrumGallery\Service\ImageService
    arguments:
      - "@webstrum_gallery.repository.image_repository"
      - "@webstrum_gallery.service.image_validator"
      - "@filesystem"

  WebstrumGallery\Controller\ImageController:
    class: WebstrumGallery\Controller\ImageController
    arguments:
      - "@webstrum_gallery.service.image_service"
